#!/bin/sh
#github-action genshdoc
#
# step1
#ArchKrisshy
#Arch Linux Automated Installer
#Code by KrisshyDesign @Indonesia
#
######################################################################################
setfont ter-v22n
time_zone="$(curl -f -s https://ipapi.co/timezone)"
ip_address=$(curl -f -s ifconfig.io)
######################################################################################
root_check() {
    if [[ "$(id -u)" != "0" ]]; then
        echo -ne "ERROR! This script must be run under the 'root' user!\n"
        exit 0
    fi
}

docker_check() {
    if awk -F/ '$2 == "docker"' /proc/self/cgroup | read -r; then
        echo -ne "ERROR! Docker container is not supported (at the moment)\n"
        exit 0
    elif [[ -f /.dockerenv ]]; then
        echo -ne "ERROR! Docker container is not supported (at the moment)\n"
        exit 0
    fi
}

arch_check() {
    if [[ ! -e /etc/arch-release ]]; then
        echo -ne "ERROR! This script must be run in Arch Linux!\n"
        exit 0
    fi
}

pacman_check() {
    if [[ -f /var/lib/pacman/db.lck ]]; then
        echo "ERROR! Pacman is blocked."
        echo -ne "If not running remove /var/lib/pacman/db.lck.\n"
        exit 0
    fi
}

background_checks() {
    root_check
    arch_check
    pacman_check
    docker_check
}


logo () {
#
echo -ne "
------------------------------------------------------------------------------------
 █████╗ ██████╗  ██████╗██╗  ██╗██╗  ██╗██████╗ ██╗███████╗███████╗██╗  ██╗██╗   ██╗
██╔══██╗██╔══██╗██╔════╝██║  ██║██║ ██╔╝██╔══██╗██║██╔════╝██╔════╝██║  ██║╚██╗ ██╔╝
███████║██████╔╝██║     ███████║█████╔╝ ██████╔╝██║███████╗███████╗███████║ ╚████╔╝
██╔══██║██╔══██╗██║     ██╔══██║██╔═██╗ ██╔══██╗██║╚════██║╚════██║██╔══██║  ╚██╔╝
██║  ██║██║  ██║╚██████╗██║  ██║██║  ██╗██║  ██║██║███████║███████║██║  ██║   ██║
╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚═╝  ╚═╝   ╚═╝
------------------------------------------------------------------------------------
                          Automated Arch Linux Installer
------------------------------------------------------------------------------------
                         Code by KrisshyDesign @Indonesia
------------------------------------------------------------------------------------
             Enjoy your Coffee this progress may take a several minutes
------------------------------------------------------------------------------------
"
echo
#
}

# Added this from Archwiki https://wiki.archlinux.org/title/System_time
timezone () {
echo -ne "
System detected your Timezone & IP Adrress to be : \n \n '$time_zone' \n '$ip_address' \n \n"
echo "Prepared the Installation ..." && sleep 5
echo "continue in 10 Seconds ..." && sleep 1
echo "Continue in 9 Seconds ..." && sleep 1
echo "Continue in 8 Seconds ..." && sleep 1
echo "Continue in 7 Seconds ..." && sleep 1
echo "continue in 6 Seconds ..." && sleep 1
echo "continue in 5 Seconds ..." && sleep 1
echo "Continue in 4 Seconds ..." && sleep 1
echo "Continue in 3 Seconds ..." && sleep 1
echo "Continue in 2 Seconds ..." && sleep 1
echo "Continue in 1 Second ..." && sleep 1
echo
echo
echo "Here we Go ...." && sleep 1
}



# Start from here
clear
clear
clear
echo -ne "
------------------------------------------------------------------------------------
 █████╗ ██████╗  ██████╗██╗  ██╗██╗  ██╗██████╗ ██╗███████╗███████╗██╗  ██╗██╗   ██╗
██╔══██╗██╔══██╗██╔════╝██║  ██║██║ ██╔╝██╔══██╗██║██╔════╝██╔════╝██║  ██║╚██╗ ██╔╝
███████║██████╔╝██║     ███████║█████╔╝ ██████╔╝██║███████╗███████╗███████║ ╚████╔╝
██╔══██║██╔══██╗██║     ██╔══██║██╔═██╗ ██╔══██╗██║╚════██║╚════██║██╔══██║  ╚██╔╝
██║  ██║██║  ██║╚██████╗██║  ██║██║  ██╗██║  ██║██║███████║███████║██║  ██║   ██║
╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚══════╝╚══════╝╚═╝  ╚═╝   ╚═╝
------------------------------------------------------------------------------------
                            Automated Arch Linux Installer
------------------------------------------------------------------------------------
                           Code by KrisshyDesign @Indonesia
------------------------------------------------------------------------------------
"
echo -ne "
------------------------------------------------------------------------------------
     Warning!!! Make sure you has setting the partition before run this script
------------------------------------------------------------------------------------
"
echo -ne "Are you has setting up the partition? \n
press Enter to continue \n
press Ctrl + c to setting the partition"
read
background_checks
clear
logo
timezone
timedatectl set-timezone $time_zone
timedatectl set-ntp true
clear
logo
echo
echo
echo -ne "
------------------------------------------------------------------------------------
          Getting mirrorlist (Indonesian Users only) from Server Krisshy
------------------------------------------------------------------------------------
"
cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
curl -o /etc/pacman.d/mirrorlist https://serverkrisshy.github.io/mirrorlist
sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
echo
echo -ne "
------------------------------------------------------------------------------------
                     Updating keyring for optimize installation
------------------------------------------------------------------------------------
"
echo
pacman-key --init
pacman-key --populate archlinux
pacman -Sy archlinux-keyring pacman-mirrorlist --noconfirm --needed
clear
logo
echo
echo -ne "
------------------------------------------------------------------------------------
                        Format & Mounting selected partition
------------------------------------------------------------------------------------
"
echo
umount -R /mnt
echo
mkfs.fat -F32 /dev/nvme0n1p1
mkfs.ext4 /dev/nvme0n1p2
mkfs.ext4 /dev/nvme0n1p3
mount /dev/nvme0n1p2 /mnt
mkdir -p /mnt/boot
mount /dev/nvme0n1p1 /mnt/boot
mkdir -p /mnt/home
mount /dev/nvme0n1p3 /mnt/home
lsblk
echo
echo
echo -ne "Is this correct? \ne
if not correct please press Ctrl + c"
read
echo
clear
logo
echo -ne "
------------------------------------------------------------------------------------
                        Installing base system to this Machine
------------------------------------------------------------------------------------
"
echo
pacstrap /mnt base base-devel linux-firmware linux linux-headers --noconfirm --needed
curl -o /mnt/root/ArchKrisshy-setup2.sh https://serverkrisshy.github.io/ArchKrisshy-setup2.sh
chmod 777 /mnt/root/ArchKrisshy-setup2.sh
echo
genfstab -U /mnt >> /mnt/etc/fstab
echo "
  Generated fstab file:
"
cat /mnt/etc/fstab
echo
echo "Enter = Yes , Ctrl+c = No \n"
read -p "Is this correct ? "
arch-chroot /mnt ./root/ArchKrisshy-setup2.sh
